### PR TITLE
Fix running roast workflows with openrouter 

### LINKED ISSUE #53: NoMethodError: undefined method `chat' for nil when using openrouter
When using openrouter setup:

```
api_provider: openrouter
api_token: $(echo $OPENROUTER_API_KEY)
```

I get the following error message:
```
🔥🔥🔥 Everyone loves a good roast 🔥🔥🔥

Configuring OpenRouter client with token from workflow
[2025-05-18 15:58:49] ERROR: Error configuring API client: unknown keyword: :api_key
Starting workflow...
Workflow: /Users/caleb/development/playground/text-adventure/.roast/git_commit.yml
Options: {}
Running targetless workflow
Prompt file for git_commit not found: 
Executing: $(git add .) (Resource type: none)
Executing: $(git diff origin/main) (Resource type: none)
Executing: Summarize the changes and update CHANGELOG.md (Resource type: none)
bundler: failed to load command: roast (/Users/caleb/.asdf/installs/ruby/3.3.5/bin/roast)


Exiting due to error: NoMethodError: undefined method `chat' for nil
/Users/caleb/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/raix-0.8.4/lib/raix/chat_completion.rb:230:in `openai_request': undefined method `chat' for nil (NoMethodError)

      Raix.configuration.openai_client.chat(parameters: params.compact.merge(model:, messages:))
```

It appears that this line is not correct in `configuration_parser`:
`OpenRouter::Client.new(api_key: configuration.api_token)`. I believe it should be using `access_token` instead.

When I change that to use `access_token`, I get this error instead.

```
🔥🔥🔥 Everyone loves a good roast 🔥🔥🔥

Configuring OpenRouter client with token from workflow
Starting workflow...
Workflow: /Users/caleb/development/playground/text-adventure/.roast/git_commit.yml
Options: {}
Running targetless workflow
Prompt file for git_commit not found: 
Executing: $(git add .) (Resource type: none)
Executing: $(git diff origin/main) (Resource type: none)
Executing: Summarize the changes and update CHANGELOG.md (Resource type: none)
bundler: failed to load command: roast (/Users/caleb/.asdf/installs/ruby/3.3.5/bin/roast)


Exiting due to error: NoMethodError: undefined method `chat' for nil
/Users/caleb/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/raix-0.8.4/lib/raix/chat_completion.rb:230:in `openai_request': undefined method `chat' for nil (NoMethodError)

      Raix.configuration.openai_client.chat(parameters: params.compact.merge(model:, messages:))
```

It appears that Roast is still trying to using an openai_client even when openrouter is specified. I'll try to get a fix up for this. Wanted to describe it in case someone else was able to get to it first.

### PR DESCRIPTION
**Pull request by xrendan**
- Use access_token instead of api_key as an initalizer
- Use a model that exists on openrouter
- Fix passing models to the openrouter client

This fixes #53

### CODE REVIEW

File: lib/roast/workflow/base_workflow.rb [hunk 1]
```diff
@@ -65,36 +68,46 @@ def final_output
         end
       end
 
+      def with_model(model)
```
Comment (xrendan) [inline lib/roast/workflow/base_workflow.rb:71]: This is weird but it's needed for how the models get passed into `raix`. 

in the `Raix::ChatCompletion` concern:

```
        response = if openai
                     openai_request(params:, model: openai, messages:)
                   else
                     openrouter_request(params:, model:, messages:)
                   end
```

It reads the model from the `openai` param that's passed into `chat_completions` but for openrouter, it takes the model value from the `model` method in the class in which it is included.

File: examples/openrouter_example/workflow.yml [hunk 2]
```diff
@@ -1,12 +1,12 @@
 name: OpenRouter Example
 api_provider: openrouter
 api_token: $(echo $OPENROUTER_API_KEY)
-model: anthropic/claude-3-haiku-20240307
+model: google/gemini-2.0-flash-001
```
Comment (xrendan) [inline examples/openrouter_example/workflow.yml:4]: this anthropic model doesn't exist on openrouter anymore

**Comment by xrendan** [comment]
I have signed the CLA!

**Comment by obie** [comment]
thank you @xrendan
